# Site settings
title: Architect Everything
email: kris.bravo@gmail.com
description: > # A think-first approach to everyday life
 modeling pieces, how they fit together, and the importance
 of understanding the connections.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bravok.github.io" # the base hostname & protocol for your site
enable_retina: true
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
  About : ['About', '/about', 'fa-anchor']
  Contact : ['Contact', '/contact', 'fa-plane']
  Author : ['Author', '/author/kris', 'fa-user']
single_footer: '<p>&copy; 2018, Kris Bravo <a href="/">latest posts</a></p>'
footer_links:
    About: ['About', '/about']
    Writer: ['Kris Bravo', '/about/kris']

# Build settings
# markdown: kramdown
